import { box, createSdf, cube, cylinder, guillermo, pushAlbedo, pushEnd, pushSphere, sphere } from "../sdf/sdfBuilder";
import { initWebgl } from "../webgl";
import { renderSdf } from "../sdf/sdfRenderer";
import * as Sdf from "../sdf/sdfRenderer";
import { createCamera, pushCameraAngle } from "../renderer";
import { randomRange } from "~aliasedFunctions";
import { DEBUG } from "~autogenerated";
import { mapN } from "~utils";
import * as assets from "~sdf/sdfAssets";
import { createSvgTextures } from "~svgTextures";

if (DEBUG) {

    const init = async () => {
        console.log("Starting Viewer");
        const canvas = document.getElementById("thecanvas") as HTMLCanvasElement;
        initWebgl(canvas);
        createCamera();
        Sdf.init();

        const ts = performance.now();
        //pushCameraAngle(0, 90);
        await assets.tree();
        //await createSvgTextures();
        console.log(`SDF data generated in ${performance.now() - ts} ms`);
    };

    init();

}