#!/bin/bash

set -euo pipefail

SCRIPT_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
cd "$SCRIPT_DIR"

DEBUG=0
DEBUG_DONT_BLOCK_INPUT=1
DEBUG_FUNCTION_NAMES=1
DEBUG_TEXTURES=1
DEBUG_MINIFY=1

# Build shaders

sed 's/export\s*const\s*\(\w*\)\s*=\s*\([^;]*\).*$/#define \1 \2/' ./src/sdf/sdfConstants.ts > ./src/shaders/sdfConstants.sh

node ./tools/palette.js > ./src/palette.ts
node ./tools/palette.js sh > ./src/shaders/palette.sh

mkdir -p ./src/shaders
echo '' > ./src/shaders/bundle.ts

minifyShader() {
	cpp -P -E -undef "$1" > ./src/shaders/out

	#Using https://github.com/laurentlb/Shader_Minifier
	if [ $DEBUG -eq 1 ]; then
		cp ./src/shaders/out ./src/shaders/outMin
	else 
		mono tools/glsl/shader_minifier.exe --no-sequence --aggressive-inlining --preserve-externals --format text -o - ./src/shaders/out > ./src/shaders/outMin	
	fi



	echo "#version 300 es" > ./src/shaders/out
	echo "precision highp float;" >> ./src/shaders/out
	echo "#define f_ float" >> ./src/shaders/out
	echo "#define _2 vec2" >> ./src/shaders/out
	echo "#define _3 vec3" >> ./src/shaders/out
	echo "#define _4 else if" >> ./src/shaders/out
	sed -e 's/float/f_/g' -e 's/vec2/_2/g' -e 's/vec3/_3/g' -e 's/else if/_4/g'  ./src/shaders/outMin >> ./src/shaders/out	
#	cat ./src/shaders/outMin  >> ./src/shaders/out
	rm ./src/shaders/outMin

	ONLY_FN=${1##*/}
	{
		echo -n "export const ${ONLY_FN%.*}$2 = \`";
		cat ./src/shaders/out;
		echo '`;' 
	} >> ./src/shaders/bundle.ts

	rm ./src/shaders/out
}

for FN in ./src/shaders/*.vert
do 
	minifyShader "$FN" Vert
done

for FN in ./src/shaders/*.frag
do 
	minifyShader "$FN" Frag
done

# Generate variables

echo '// This file is autogenerated' > ./src/autogenerated.ts

if [ $DEBUG -eq 1 ]; then
  echo 'export const DEBUG = true;' >> ./src/autogenerated.ts
else 
  echo 'export const DEBUG = false;' >> ./src/autogenerated.ts
fi

if [ $DEBUG -eq 1 ] && [ $DEBUG_TEXTURES -eq 1 ]; then
  echo 'export const DEBUG_TEXTURES = true;' >> ./src/autogenerated.ts
else 
  echo 'export const DEBUG_TEXTURES = false;'>> ./src/autogenerated.ts
fi

if [ $DEBUG -eq 1 ] && [ $DEBUG_DONT_BLOCK_INPUT -eq 1 ]; then
  echo 'export const DEBUG_DONT_BLOCK_INPUT = true;' >> ./src/autogenerated.ts
else 
  echo 'export const DEBUG_DONT_BLOCK_INPUT = false;'>> ./src/autogenerated.ts
fi

# Generate levels 

node ./tools/parseLevels.js > ./src/levelDefinitions.ts ./assets/levels.levels

# Lint

if [ $DEBUG -eq 0 ]; then
	npx tsc --noEmit --strict
fi

# Bundle

npx esbuild src/index.ts --format=iife --bundle --outfile=dist/out.js


# The build of the editor

mkdir -p dist/viewer
cp src/SdfView/index.html dist/viewer/
cp livejs/live.js dist/viewer/
npx esbuild src/SdfView/index.ts --format=iife --bundle --outfile=dist/viewer/index.js



# Minify
	
mkdir -p dist/entry
cd dist/entry

if [ $DEBUG -eq 0 ] || [ $DEBUG_MINIFY -eq 1 ]; then
	TERSER_EXTRA_OPTIONS='--compress drop_console,passes=3'

	if [ $DEBUG -eq 1 ]; then
		TERSER_EXTRA_OPTIONS='--source-map url=inline'

		if [ $DEBUG_FUNCTION_NAMES -eq 1 ]; then
			TERSER_EXTRA_OPTIONS="${TERSER_EXTRA_OPTIONS} --keep-fnames"
		fi 
	fi 

	npx terser ../out.js --ecma 2021 --mangle --toplevel --mangle-props keep_quoted ${TERSER_EXTRA_OPTIONS} -o out.js
else 
	cp ../out.js out.js
fi

# Todo: Drop const from shaders before this search and replace

#JS_CODE=$(sed 's/\bconst\b/let/g' < out.js | sed 's/\bvar\b/let/g')

if [ $DEBUG -eq 0 ]; then
	# CUR FIT: -Zab9 -Zlr930 -Zmc4 -Zpr13 -S0,1,2,3,4,7,13,21,42,213,305,330	npx roadroller -O2 -t js out.js -o out.rr.js
	mv -f out.rr.js out.js
	echo "nothings"
fi

JS_CODE=$(cat out.js)

printf '\xEF\xBB\xBF' > "index.html"	# A leading UTF-8 Byte Order Mark serves to identify the character encoding.

cat <<-EOF | tr -d '\n' >> "index.html"
	<!DOCTYPE html>
	<style>span{font-size:100px;animation:spin 1s infinite;}@keyframes spin{from{transform:rotate(0deg);}to{transform:rotate(360deg);}}
	
	canvas {
	max-width: 100%;
    max-height: 100%;
    bottom: 0;
    left: 0;
    margin: auto;
    overflow: auto;
    position: fixed;
    right: 0;
    top: 0;
	width: 100%;
    object-fit: contain;
	}
	</style>
	<title>DEATHWISH</title>
	<script>${JS_CODE}</script>
EOF


printf '\n' >> "index.html"	# Append a newline to make a POSIX‐compliant text file.

rm out.js


