import { DEBUG } from "./autogenerated";

export const sqrt = Math.sqrt;
export const assert = DEBUG ? ((cond: boolean, msg?: string) => cond || ((() => { throw new Error(msg ?? "No Error Message") })())) : (() => { });
export const sin = Math.sin;
export const cos = Math.cos;
export const atan2 = Math.atan2;
export const floor = Math.floor;
export const fract = (x: number) => {
    const r = x - floor(x);
    return r < 1 ? r : 0.99999999999; // Hackity HACK!
}
export const max = Math.max;
export const min = Math.min;
export const acos = Math.acos;
export const asin = Math.asin;
export const abs = Math.abs;
export const clamp = (x: number, a: number, b: number) => max(a, min(b, x));
export const random = Math.random;
export const randomRange = (a: number, b: number) => a + random() * (b - a);
export const Pi = Math.PI;
export const PiHalf = Pi / 2;
export const TwoPi = 2.0 * Pi;
export const Deg = Pi / 180;
export const Rad = 180 / Pi;
