import { viewResolution } from "./constants";
import { DEBUG } from "./autogenerated";
import * as glEnum from "./webglEnums";
import { assert } from "~aliasedFunctions";

export let gl: WebGL2RenderingContext;

const glReverseEnumLookUp = (value: any) => {
    let k = Object.getOwnPropertyNames(WebGL2RenderingContext).find(x => (WebGL2RenderingContext as any)[x] === value);
    return k || "<ENUM VALUE NOT FOUND>";
}

export const initWebgl = (canvas: HTMLCanvasElement) => {
    console.log("JS13k2022 - Debug Build - WebGL Init");

    assert(gl == null || gl == undefined);

    gl = canvas.getContext("webgl2", { alpha: false, powerPreference: "high-performance", antialias: true }) as WebGL2RenderingContext;
    if (!gl) {
        alert("WebGL 2 needed.");
        throw new Error();
    }
    gl.clearColor(0.5, 0, 0.5, 1);
    gl.viewport(0, 0, canvas.width, canvas.height);
}


export const loadShader = (typeId: number, source: string) => {
    const shader = gl.createShader(typeId) as WebGLShader;
    gl.shaderSource(shader, source);
    gl.compileShader(shader);

    if (DEBUG) {
        if (!gl.getShaderParameter(shader, glEnum.COMPILE_STATUS)) {
            console.warn(`FAILED SHADER: (TYPE ${glReverseEnumLookUp(typeId)})`);
            console.warn(`ERROR LOG`, gl.getShaderInfoLog(shader));
            console.warn("============================================");
            console.warn(source);
            gl.deleteShader(shader);
            throw new Error("SHADER COMPILATION FAILED!");
        }
    }
    return shader;
}

export const createProgramWithShaders = (shaders: [WebGLShader, WebGLShader]) => {
    const shaderProgram = gl.createProgram() as WebGLProgram;
    shaders.forEach(x => gl.attachShader(shaderProgram, x));
    gl.linkProgram(shaderProgram);

    if (DEBUG) {
        if (!gl.getProgramParameter(shaderProgram, glEnum.LINK_STATUS)) {
            console.error('Unable to link the shader program: ' + gl.getProgramInfoLog(shaderProgram));
            return null;
        }
    }

    gl.validateProgram(shaderProgram);

    if (DEBUG) {
        if (!gl.getProgramParameter(shaderProgram, glEnum.VALIDATE_STATUS)) {
            console.error('Unable to validate the shader program: ' + gl.getProgramInfoLog(shaderProgram));
            return null;
        }
    }

    shaders.forEach(x => gl.deleteShader(x));

    if (DEBUG) {
        console.log("Shader program linked");
    }

    return shaderProgram;
};

export interface WebGLShaderBundle {
    program: WebGLProgram;
    uniforms: { [index: string]: WebGLUniformLocation; };
};

export const createProgram = (vsSrc: string, fsSrc: string) => {
    const vertexShader = loadShader(glEnum.VERTEX_SHADER, vsSrc) as WebGLShader;
    const fragmentShader = loadShader(glEnum.FRAGMENT_SHADER, fsSrc) as WebGLShader;

    return {
        program: createProgramWithShaders([vertexShader, fragmentShader]) as WebGLProgram,
        uniforms: {},
    } as WebGLShaderBundle;
};

export const getUniformLocation = (prog: WebGLShaderBundle, name: string) => {
    prog.uniforms[name] = gl.getUniformLocation(prog.program, name) as WebGLUniformLocation;
};

export const createTexture = (tw: number, th: number, internalFormat: number, pixels: ArrayBufferView | null) => {
    const tex = gl.createTexture() as WebGLTexture;
    gl.bindTexture(glEnum.TEXTURE_2D, tex);

    assert(internalFormat == glEnum.RGBA || internalFormat == glEnum.RGBA32F);

    gl.texImage2D(glEnum.TEXTURE_2D, 0, internalFormat,
        tw, th, 0,
        glEnum.RGBA, internalFormat == glEnum.RGBA ? glEnum.UNSIGNED_BYTE : glEnum.FLOAT, pixels);

    gl.texParameteri(glEnum.TEXTURE_2D, glEnum.TEXTURE_MIN_FILTER, glEnum.NEAREST);
    gl.texParameteri(glEnum.TEXTURE_2D, glEnum.TEXTURE_MAG_FILTER, glEnum.NEAREST);

    gl.texParameteri(glEnum.TEXTURE_2D, glEnum.TEXTURE_WRAP_S, glEnum.CLAMP_TO_EDGE);
    gl.texParameteri(glEnum.TEXTURE_2D, glEnum.TEXTURE_WRAP_T, glEnum.CLAMP_TO_EDGE);
    return tex;
};

export const createTextureArray = (tw: number, th: number, nLayers: number, internalFormat: number) => {
    const tex = gl.createTexture() as WebGLTexture;
    gl.bindTexture(glEnum.TEXTURE_2D_ARRAY, tex);

    assert(internalFormat == glEnum.RGBA8);


    const levels = Math.log2(tw) + 1;

    gl.texStorage3D(glEnum.TEXTURE_2D_ARRAY, levels, internalFormat, tw, th, nLayers);

    gl.texParameteri(glEnum.TEXTURE_2D_ARRAY, glEnum.TEXTURE_MIN_FILTER, glEnum.LINEAR_MIPMAP_LINEAR);
    gl.texParameteri(glEnum.TEXTURE_2D_ARRAY, glEnum.TEXTURE_MAG_FILTER, glEnum.LINEAR);

    gl.texParameteri(glEnum.TEXTURE_2D_ARRAY, glEnum.TEXTURE_WRAP_S, glEnum.CLAMP_TO_EDGE);
    gl.texParameteri(glEnum.TEXTURE_2D_ARRAY, glEnum.TEXTURE_WRAP_T, glEnum.CLAMP_TO_EDGE);

    return {
        tex,
        w: tw,
        h: th,
        numLayers: nLayers,
        curLayer: 0,
        internalFormat,
    };
};

export type TextureArray = ReturnType<typeof createTextureArray>;

export const pushTextureArrayLayer = (tex: TextureArray, pixels: ArrayBufferView) => {
    assert(tex.curLayer < tex.numLayers, "Texture array overflow!");
    gl.bindTexture(glEnum.TEXTURE_2D_ARRAY, tex.tex);
    gl.texSubImage3D(glEnum.TEXTURE_2D_ARRAY, 0, 0, 0, tex.curLayer++, tex.w, tex.h, 1, glEnum.RGBA, glEnum.UNSIGNED_BYTE, pixels);
};

export const setFramebuffer = (fb: WebGLFramebuffer | null, w: number, h: number) => {
    gl.bindFramebuffer(gl.FRAMEBUFFER, fb);
    gl.viewport(0, 0, w, h);
};

export const createUBO = (size: number) => {
    const buffer = gl.createBuffer() as WebGLBuffer;
    gl.bindBuffer(glEnum.UNIFORM_BUFFER, buffer);
    gl.bufferData(glEnum.UNIFORM_BUFFER, size, glEnum.DYNAMIC_DRAW);
    return buffer;
};